language: node_js
node_js:
  - "node"
install:
  - npm i -g npm@5.8.0
  - npm ci
deploy:
  provider: npm
  email: jculloty@gmail.com
  api_key:
    secure: lPNpIDEUWS6XedgAYlfJsWm7a71DL+TyoTKlLMyOl0uia+rzO5EWZzWyw4cF7+ZBUj1WLA5JOUvvDfwh224ZO1lS58bur2RD7/C8SlyCPY85hUPu/9412o9wXTRjHzMIifk5IEO/OQiwj0JPwnWirTktzqcNq0PyisV5Xk39a5a6nBxXDuzI8C9PEcKa8s0UiRCuf+920h7KAKsKyEyBO1/ocG/ZerrEgC/RpzBaFlTJw+i6XP2PbOBw8ztQhVT7JHef1dKdeLmw4zt1Jc5bTAYVmfS4OTRuF9tbXc2RBcn4Itrc1EwOFU781iHwW61cIlZYZQJB9RLvRgwqurcJ8WYvQ4VtBkJ4oVv9qfu2XIaryMkScKVRC5awLWhV1z4oOITsU2yt4fTjDUYx87q4/tU6qnb8epg0BBOlVS9YNgh1gHfB+R5GAjmcqwRE1oW27bZLuI119dFZLg6nQXPXrqKGTzOzP/4c1eKuq53TMbFhKsS0u4z0uIIVtc9SeNLyIiTi6pumF9jZ+Jc9p5OFhw/iV7Ob0PXDCpYSqmBrrlkt80z5WvQm5ndTf7Buzc8Y6Mh3AwidR4k3rS51oelR2Wn88O8uSTiou1/0lmrMI1Duz4ES3lkCOZZgC7YIF/vLIDmE1hSP6Yx2J7gHaMC/1dwA1gXLDlCVmw9SxDCfoKs=
  on:
    repo: jculloty/redux-reducer-selectors
